version: '3'

services:

  staff:
    build: ./staff
    container_name: staff
    # Connect to the barq network
    networks:
      - barq-server_barq-net
      # Ensure that node_modules aren’t unnecessarily copied
    volumes:
     - ./staff:/app
     - /app/node_modules
    # Set the container name
    ports:
      # Map the react app at 3000 to 3000 on host
      - "3000:3000"

  customer:
    build: ./customer
    container_name: customer
    # Ensure that node_modules aren’t unnecessarily copied
    volumes:
     - ./customer:/app
     - /app/node_modules
    # Connect to the barq network
    networks:
      - barq-server_barq-net
    ports:
      # Map the react app at 3000 to 3002 on host
      - "3002:3000"

  admin:
    build: ./admin
    container_name: admin
    # Ensure that node_modules aren’t unnecessarily copied
    volumes:
     - ./admin:/app
     - /app/node_modules
    # Connect to the barq network
    networks:
      - barq-server_barq-net
    ports:
      # Map the react app at 3000 to 3003 on host
      - "3003:3000"

networks: 

  barq-server_barq-net:
    external: true
